<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-PB9LG37" failures="2" tests="2" name="Default test(failed)(failed)" time="0.349" errors="0" timestamp="2022-03-22T19:30:25 IST">
  <testcase classname="testNG_Failed_xml.Failed_xml_Study" name="TC4" time="0.016">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testNG_Failed_xml.Failed_xml_Study.TC4(Failed_xml_Study.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC4 -->
  <testcase classname="testNG_Failed_xml.Failed_xml_Study" name="TC2" time="0.218">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testNG_Failed_xml.Failed_xml_Study.TC2() didn&amp;apos;t finish within the time-out 200">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNG_Failed_xml.Failed_xml_Study.TC2() didn't finish within the time-out 200
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- TC2 -->
  <testcase classname="testNG_Failed_xml.Failed_xml_Study" name="TC5" time="0.0">
    <ignored/>
  </testcase> <!-- TC5 -->
  <testcase classname="testNG_Failed_xml.Failed_xml_Study" name="TC1" time="0.0">
    <ignored/>
  </testcase> <!-- TC1 -->
  <testcase classname="testNG_Failed_xml.Failed_xml_Study" name="TC3" time="0.0">
    <ignored/>
  </testcase> <!-- TC3 -->
</testsuite> <!-- Default test(failed)(failed) -->
